import pygame

# Screen Dimensions
SCREEN_WIDTH = 384
SCREEN_HEIGHT = 640
FPS = 60

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARK_GRAY = (50, 50, 50)
GOLD = (245, 180, 50)

# Game States & Modes
STATE_HOME = "HOME"
STATE_PLAYING = "PLAYING"
STATE_PAUSED = "PAUSED"
STATE_GAMEOVER = "GAMEOVER"

MODE_CASUAL = "CASUAL"
MODE_UNLIMITED = "UNLIMITED"

GAME_DURATION = 60.0  # 1 Minute gameplay for Casual mode (seconds)

# Recipe Stages
STAGE_IDLE = "IDLE"
STAGE_BOWL_CENTER = "BOWL_CENTER"
STAGE_HAS_FLOUR = "HAS_FLOUR"
STAGE_HAS_EGG = "HAS_EGG"
STAGE_HAS_BUTTER = "HAS_BUTTER"
STAGE_HAS_SUGAR = "HAS_SUGAR"
STAGE_WHISKING = "WHISKING"
STAGE_MIXED = "MIXED"
STAGE_DOUGH_READY = "DOUGH_READY"
STAGE_CUT_DOUGH = "CUT_DOUGH"
STAGE_HAS_CHOCOCHIP = "HAS_CHOCOCHIP"
STAGE_BAKING = "BAKING"
STAGE_COOKIE_DONE = "COOKIE_DONE"
STAGE_SERVED = "SERVED"

# Customer Entrance & Exit Animation Config
CUSTOMER_TARGET_X = 15
CUSTOMER_START_X = -200
CUSTOMER_ANIM_DURATION = 0.6  # Seconds
CUSTOMER_EXIT_DURATION = 1.5  # Exit animation duration (seconds)

# Baking QTE Config
QTE_BAR_WIDTH = 240
QTE_BAR_HEIGHT = 24
QTE_BAR_X = (SCREEN_WIDTH - QTE_BAR_WIDTH) // 2
QTE_BAR_Y_OFFSET = 250
QTE_DURATION = 3.0      # 3.0 seconds to travel across

# QTE Zone Boundaries (normalized 0.0 - 1.0)
QTE_ZONE_BAD_START = 0.40
QTE_ZONE_BAD_END = 0.85

QTE_ZONE_GOOD_START = 0.53
QTE_ZONE_GOOD_END = 0.77

QTE_ZONE_PERFECT_START = 0.62
QTE_ZONE_PERFECT_END = 0.69

# Whisk Mini-Game Config
WHISK_REQUIRED_CLICKS = 15
WHISK_TIME_LIMIT = 10.0  # 10 seconds max time limit
OVEN_SIZE = (120, 120)
NUM_OVEN_FRAMES = 6
OVEN_FRAME_WIDTH = 32
OVEN_FRAME_HEIGHT = 32
OVEN_FRAME_DURATION = 3.0  # 3 seconds per frame
